### ISSUE TITLE
MongoDb not connecting to Heroku

### ISSUE THREAD

**Issue by ChelcieDeAlmeida** [ChelcieDeAlmeida/pizza-hunt#5]
Once the app is deployed, mongoDb doesn't seem to be responding. When the user creates a pizza and clicks on "See All pizzas," users will be met with a page without created pizzas

**Comment by PetitsPoissons** [comment]
Hi Chelcie, this is Sandrine from AskBCS. Ok, this is wild: I cloned your repo and deployed it on heroku, using my own mongodb and heroku accounts, and it works! See for yourself: https://chelcie-pizza.herokuapp.com/
The only thing I did differently from what we did together is that I actually did not create a db ahead of time as I recall from other apps I've built that it is not necessary.

**Comment by ChelcieDeAlmeida** [comment]
Interesting, when you say you didn't create a db ahead of time. Do you mean during the mongo atlas process?

**Comment by PetitsPoissons** [comment]
Yes. I just copied the connection string and replaced with my password and a dbname (I chose pizza-hunt, but it shouldn't matter). Interestingly, it created one collection with name `pizzas` (pluralized).

**Comment by ChelcieDeAlmeida** [comment]
This is odd indeed. I certainly appreciate you looking into this. Heroku can get a little silly at times so perhaps I just need to mess with it a bit...or break it
